package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PageWallPostsId generated by hbm2java
 */
@Embeddable
public class PageWallPostsId  implements java.io.Serializable {


     private int pageWallPostId;
     private int pageId;

    public PageWallPostsId() {
    }

    public PageWallPostsId(int pageWallPostId, int pageId) {
       this.pageWallPostId = pageWallPostId;
       this.pageId = pageId;
    }
   


    @Column(name="page_wall_post_id", nullable=false)
    public int getPageWallPostId() {
        return this.pageWallPostId;
    }
    
    public void setPageWallPostId(int pageWallPostId) {
        this.pageWallPostId = pageWallPostId;
    }


    @Column(name="page_id", nullable=false)
    public int getPageId() {
        return this.pageId;
    }
    
    public void setPageId(int pageId) {
        this.pageId = pageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PageWallPostsId) ) return false;
		 PageWallPostsId castOther = ( PageWallPostsId ) other; 
         
		 return (this.getPageWallPostId()==castOther.getPageWallPostId())
 && (this.getPageId()==castOther.getPageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPageWallPostId();
         result = 37 * result + this.getPageId();
         return result;
   }   


}


