package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendsId generated by hbm2java
 */
@Embeddable
public class FriendsId  implements java.io.Serializable {


     private int friendsId;
     private int userId;
     private int friendId;

    public FriendsId() {
    }

    public FriendsId(int friendsId, int userId, int friendId) {
       this.friendsId = friendsId;
       this.userId = userId;
       this.friendId = friendId;
    }
   


    @Column(name="friends_id", nullable=false)
    public int getFriendsId() {
        return this.friendsId;
    }
    
    public void setFriendsId(int friendsId) {
        this.friendsId = friendsId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="friend_id", nullable=false)
    public int getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(int friendId) {
        this.friendId = friendId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendsId) ) return false;
		 FriendsId castOther = ( FriendsId ) other; 
         
		 return (this.getFriendsId()==castOther.getFriendsId())
 && (this.getUserId()==castOther.getUserId())
 && (this.getFriendId()==castOther.getFriendId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFriendsId();
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getFriendId();
         return result;
   }   


}


