package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendRequestsId generated by hbm2java
 */
@Embeddable
public class FriendRequestsId  implements java.io.Serializable {


     private int friendRequestId;
     private int userId;
     private int friendId;

    public FriendRequestsId() {
    }

    public FriendRequestsId(int friendRequestId, int userId, int friendId) {
       this.friendRequestId = friendRequestId;
       this.userId = userId;
       this.friendId = friendId;
    }
   


    @Column(name="friend_request_id", nullable=false)
    public int getFriendRequestId() {
        return this.friendRequestId;
    }
    
    public void setFriendRequestId(int friendRequestId) {
        this.friendRequestId = friendRequestId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="friend_id", nullable=false)
    public int getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(int friendId) {
        this.friendId = friendId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendRequestsId) ) return false;
		 FriendRequestsId castOther = ( FriendRequestsId ) other; 
         
		 return (this.getFriendRequestId()==castOther.getFriendRequestId())
 && (this.getUserId()==castOther.getUserId())
 && (this.getFriendId()==castOther.getFriendId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFriendRequestId();
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getFriendId();
         return result;
   }   


}


