package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Likes generated by hbm2java
 */
@Entity
@Table(name="likes"
    ,catalog="fakebook"
)
public class Likes  implements java.io.Serializable {


     private Integer likeId;
     private Pages pagesByPageId;
     private Users users;
     private Pages pagesByOtherId;
     private Date likeDate;
     private int active;

    public Likes() {
    }

	
    public Likes(Pages pagesByPageId, Date likeDate, int active) {
        this.pagesByPageId = pagesByPageId;
        this.likeDate = likeDate;
        this.active = active;
    }
    public Likes(Pages pagesByPageId, Users users, Pages pagesByOtherId, Date likeDate, int active) {
       this.pagesByPageId = pagesByPageId;
       this.users = users;
       this.pagesByOtherId = pagesByOtherId;
       this.likeDate = likeDate;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="like_id", unique=true, nullable=false)
    public Integer getLikeId() {
        return this.likeId;
    }
    
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="page_id", nullable=false)
    public Pages getPagesByPageId() {
        return this.pagesByPageId;
    }
    
    public void setPagesByPageId(Pages pagesByPageId) {
        this.pagesByPageId = pagesByPageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="other_id")
    public Pages getPagesByOtherId() {
        return this.pagesByOtherId;
    }
    
    public void setPagesByOtherId(Pages pagesByOtherId) {
        this.pagesByOtherId = pagesByOtherId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="like_date", nullable=false, length=19)
    public Date getLikeDate() {
        return this.likeDate;
    }
    
    public void setLikeDate(Date likeDate) {
        this.likeDate = likeDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


