package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FriendRequests generated by hbm2java
 */
@Entity
@Table(name="friend_requests"
    ,catalog="fakebook"
)
public class FriendRequests  implements java.io.Serializable {


     private FriendRequestsId id;
     private Users usersByFriendId;
     private Users usersByUserId;
     private Date friendRequestDate;
     private int active;

    public FriendRequests() {
    }

    public FriendRequests(FriendRequestsId id, Users usersByFriendId, Users usersByUserId, Date friendRequestDate, int active) {
       this.id = id;
       this.usersByFriendId = usersByFriendId;
       this.usersByUserId = usersByUserId;
       this.friendRequestDate = friendRequestDate;
       this.active = active;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="friendRequestId", column=@Column(name="friend_request_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="friendId", column=@Column(name="friend_id", nullable=false) ) } )
    public FriendRequestsId getId() {
        return this.id;
    }
    
    public void setId(FriendRequestsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="friend_id", nullable=false, insertable=false, updatable=false)
    public Users getUsersByFriendId() {
        return this.usersByFriendId;
    }
    
    public void setUsersByFriendId(Users usersByFriendId) {
        this.usersByFriendId = usersByFriendId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="friend_request_date", nullable=false, length=19)
    public Date getFriendRequestDate() {
        return this.friendRequestDate;
    }
    
    public void setFriendRequestDate(Date friendRequestDate) {
        this.friendRequestDate = friendRequestDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


