package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Friends generated by hbm2java
 */
@Entity
@Table(name="friends"
    ,catalog="fakebook"
)
public class Friends  implements java.io.Serializable {


     private FriendsId id;
     private Users usersByFriendId;
     private Users usersByUserId;
     private Date friendDate;
     private int active;

    public Friends() {
    }

    public Friends(FriendsId id, Users usersByFriendId, Users usersByUserId, Date friendDate, int active) {
       this.id = id;
       this.usersByFriendId = usersByFriendId;
       this.usersByUserId = usersByUserId;
       this.friendDate = friendDate;
       this.active = active;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="friendsId", column=@Column(name="friends_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="friendId", column=@Column(name="friend_id", nullable=false) ) } )
    public FriendsId getId() {
        return this.id;
    }
    
    public void setId(FriendsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="friend_id", nullable=false, insertable=false, updatable=false)
    public Users getUsersByFriendId() {
        return this.usersByFriendId;
    }
    
    public void setUsersByFriendId(Users usersByFriendId) {
        this.usersByFriendId = usersByFriendId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="friend_date", nullable=false, length=19)
    public Date getFriendDate() {
        return this.friendDate;
    }
    
    public void setFriendDate(Date friendDate) {
        this.friendDate = friendDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


