package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ignores generated by hbm2java
 */
@Entity
@Table(name="ignores"
    ,catalog="fakebook"
)
public class Ignores  implements java.io.Serializable {


     private Integer ignoreId;
     private Pages pages;
     private Users usersByUserId;
     private Users usersByIgnoredUserId;
     private Date ignoreDate;
     private int active;

    public Ignores() {
    }

	
    public Ignores(Users usersByUserId, Date ignoreDate, int active) {
        this.usersByUserId = usersByUserId;
        this.ignoreDate = ignoreDate;
        this.active = active;
    }
    public Ignores(Pages pages, Users usersByUserId, Users usersByIgnoredUserId, Date ignoreDate, int active) {
       this.pages = pages;
       this.usersByUserId = usersByUserId;
       this.usersByIgnoredUserId = usersByIgnoredUserId;
       this.ignoreDate = ignoreDate;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ignore_id", unique=true, nullable=false)
    public Integer getIgnoreId() {
        return this.ignoreId;
    }
    
    public void setIgnoreId(Integer ignoreId) {
        this.ignoreId = ignoreId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ignored_page_id")
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ignored_user_id")
    public Users getUsersByIgnoredUserId() {
        return this.usersByIgnoredUserId;
    }
    
    public void setUsersByIgnoredUserId(Users usersByIgnoredUserId) {
        this.usersByIgnoredUserId = usersByIgnoredUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ignore_date", nullable=false, length=19)
    public Date getIgnoreDate() {
        return this.ignoreDate;
    }
    
    public void setIgnoreDate(Date ignoreDate) {
        this.ignoreDate = ignoreDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


