package com.cooksys.fbws.hibernate;
// Generated Jul 9, 2015 2:35:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WallPostLikes generated by hbm2java
 */
@Entity
@Table(name="wall_post_likes"
    ,catalog="fakebook"
)
public class WallPostLikes  implements java.io.Serializable {


     private Integer wallPostLikeId;
     private WallPosts wallPosts;
     private Pages pages;
     private Users users;
     private Date likeDate;
     private int active;

    public WallPostLikes() {
    }

    public WallPostLikes(WallPosts wallPosts, Pages pages, Users users, Date likeDate, int active) {
       this.wallPosts = wallPosts;
       this.pages = pages;
       this.users = users;
       this.likeDate = likeDate;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="wall_post_like_id", unique=true, nullable=false)
    public Integer getWallPostLikeId() {
        return this.wallPostLikeId;
    }
    
    public void setWallPostLikeId(Integer wallPostLikeId) {
        this.wallPostLikeId = wallPostLikeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wall_post_id", nullable=false)
    public WallPosts getWallPosts() {
        return this.wallPosts;
    }
    
    public void setWallPosts(WallPosts wallPosts) {
        this.wallPosts = wallPosts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="page_id", nullable=false)
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="like_date", nullable=false, length=19)
    public Date getLikeDate() {
        return this.likeDate;
    }
    
    public void setLikeDate(Date likeDate) {
        this.likeDate = likeDate;
    }

    
    @Column(name="active", nullable=false)
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


